/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/Research/index'
import { Route as PublicationIndexRouteImport } from './routes/Publication/index'
import { Route as FunFactsIndexRouteImport } from './routes/FunFacts/index'
import { Route as ContactIndexRouteImport } from './routes/Contact/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/Research/',
  path: '/Research/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationIndexRoute = PublicationIndexRouteImport.update({
  id: '/Publication/',
  path: '/Publication/',
  getParentRoute: () => rootRouteImport,
} as any)
const FunFactsIndexRoute = FunFactsIndexRouteImport.update({
  id: '/FunFacts/',
  path: '/FunFacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/Contact/',
  path: '/Contact/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Contact': typeof ContactIndexRoute
  '/FunFacts': typeof FunFactsIndexRoute
  '/Publication': typeof PublicationIndexRoute
  '/Research': typeof ResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Contact': typeof ContactIndexRoute
  '/FunFacts': typeof FunFactsIndexRoute
  '/Publication': typeof PublicationIndexRoute
  '/Research': typeof ResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Contact/': typeof ContactIndexRoute
  '/FunFacts/': typeof FunFactsIndexRoute
  '/Publication/': typeof PublicationIndexRoute
  '/Research/': typeof ResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Contact' | '/FunFacts' | '/Publication' | '/Research'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Contact' | '/FunFacts' | '/Publication' | '/Research'
  id:
    | '__root__'
    | '/'
    | '/Contact/'
    | '/FunFacts/'
    | '/Publication/'
    | '/Research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  FunFactsIndexRoute: typeof FunFactsIndexRoute
  PublicationIndexRoute: typeof PublicationIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Research/': {
      id: '/Research/'
      path: '/Research'
      fullPath: '/Research'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Publication/': {
      id: '/Publication/'
      path: '/Publication'
      fullPath: '/Publication'
      preLoaderRoute: typeof PublicationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FunFacts/': {
      id: '/FunFacts/'
      path: '/FunFacts'
      fullPath: '/FunFacts'
      preLoaderRoute: typeof FunFactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact/': {
      id: '/Contact/'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  FunFactsIndexRoute: FunFactsIndexRoute,
  PublicationIndexRoute: PublicationIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
